name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo a
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python shell step
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-bash-commands:
    runs-on: windows-latest
    steps:
      - name: Power shell example
        run: Get-Location
      - name: Bash on Windows example
        run: pwd
        shell: bash